Fix: Add missing Slide magic word to fix 500 error
The #Slide parser function was registered in SlideHooks.php but the
'Slide' magic word was not defined in Layers.i18n.magic.php, causing
an UnexpectedValueException on page load:

  Error: invalid magic word 'Slide'

This broke the entire wiki on MediaWiki 1.44.6.

Added the 'Slide' magic word definition to fix the issue.